config/routes.rb
Rails.application.routes.draw do
  resources :post_tags
  resources :categories
  resources :posts
  resources :users



  post '/posts/:id/read', to: 'posts#read',  as: 'post_read'
  post '/posts/:id/unread', to: 'posts#unread',  as: 'post_unread'
  get '/allthefeels', to: 'application#allthefeels', as: 'analytics'



  resources :categories do
    resources :posts
  end


  root 'application#home', as: 'home'
  get '/login', to: "sessions#new", as: 'login'
  post '/login', to: "sessions#create"
  delete '/sessions', to: "sessions#destroy", as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, :foreign_key => 'sender_id'
  has_many :opens, :foreign_key => 'recipient_id', :class_name => "Post"
  has_many :categories, through: :opens
  # looking at all the categories for which a person has received an OpenWhen
  has_many :visits

  has_secure_password

  validates :name, :username, :email, presence: true
  validates :username, uniqueness: true
  validates :email, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create



  def average_duration
    if self.visits.count > 1
      user_durations = self.visits[0...-1].map {|visit| (visit.ended_at - visit.started_at)/60}
      total_user_duration = user_durations.inject(:+)
      (total_user_duration / self.visits[0...-1].count).round(2)
    else
      total_user_duration = (Time.now - self.visits[0].started_at)/60
    end
  end

  def max_duration
    if self.visits.count > 1
      user_durations = self.visits[0...-1].map {|visit| (visit.ended_at - visit.started_at)/60}
      user_durations.max.round(2)
    else
      user_duration = (Time.now - self.visits[0].started_at)/60
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      session[:user_id] = @user.id
      visit = Visit.create(user_id: @user.id, started_at: Time.now)
      session[:visit_id] = visit.id
      redirect_to home_path
    else
      flash[:message] = "Please try a unique username / email combination or your email is invalid"
      redirect_to new_user_path
    end
  end

  def edit
    current_user
  end


  def show
    @user = User.find_by(id: params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="col-sm-4">

<%= form_for @user do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "name", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "username", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, placeholder: "example@example.com", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "your password here", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: "confirm password", class: "form-control" %>
</div>
<%= f.submit "Save Changes", class: 'btn btn-large btn-primary' %>
<% end %>

</div>

app/views/users/new.html.erb
<p><%= flash[:message] %></p>

<div class="col-sm-4">

<%= form_for @user do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "name", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "username", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, placeholder: "example@example.com", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "your password here", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: "confirm password", class: "form-control" %>
</div>
<%= f.submit "Sign up", class: 'btn btn-large btn-primary' %>
<% end %>

</div>

app/views/users/show.html.erb
<div class="container">
        <div class="col-md-6">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-md-12">
                        <h4><%= current_user.name.titleize %></h4>
                        <p>
                          <i class="glyphicon glyphicon-user"></i> username: <%= current_user.username %>
                          <br />
                            <i class="glyphicon glyphicon-envelope"></i> <%= current_user.email %>
                            <br />
                            <i class="glyphicon glyphicon-calendar"></i> joined <%= current_user.created_at.strftime("%B %d, %Y at %l:%M %P") %> </p>
                            <%= button_to "Edit account", edit_user_path(current_user), method: :get, class: 'btn btn-large btn-primary' %>
              </div>
            </div>
        </div>
    </div>

<div class="col-md-6">
  <div class="well well-sm">
      <div class="row">
          <div class="col-md-12">
            <h4> Your Notes </h4>
            <p>
              <i class="glyphicon glyphicon-envelope"></i> <strong> Sent: </strong> <%= current_user.posts.count %>  ||
              <i class="glyphicon glyphicon-envelope"></i><strong> Received: </strong><%= current_user.opens.count %>
              <br />
              <i class="glyphicon glyphicon-time"></i> <strong> Longest visit: </strong><%= current_user.max_duration.round(2) %> minutes
              <br />
              <i class="glyphicon glyphicon-time"></i> <strong> Average visit: </strong><%= current_user.average_duration.round(2) %> minutes
              <br />
              <%= button_to "See more stats", analytics_path, method: :get, class: 'btn btn-large btn-primary' %>
          </div>
      </div>
  </div>
</div>

</div>