config/routes.rb
Rails.application.routes.draw do
  resources :post_tags
  resources :categories
  resources :posts
  resources :users



  post '/posts/:id/read', to: 'posts#read',  as: 'post_read'
  post '/posts/:id/unread', to: 'posts#unread',  as: 'post_unread'
  get '/allthefeels', to: 'application#allthefeels', as: 'analytics'



  resources :categories do
    resources :posts
  end


  root 'application#home', as: 'home'
  get '/login', to: "sessions#new", as: 'login'
  post '/login', to: "sessions#create"
  delete '/sessions', to: "sessions#destroy", as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# class Open < ApplicationRecord
#
#   belongs_to :post
#   belongs_to :recipient, :class_name => "User"
#
#
# end




class Post < ApplicationRecord
  has_many :post_tags
  has_many :tags, through: :post_tags
  belongs_to :sender, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
  belongs_to :category
  accepts_nested_attributes_for :tags

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @post.tags.build(name: "")
    @post.tags.build(name: "")
    all_senders_and_receivers = []
    current_user.posts.each do |post|
      all_senders_and_receivers << post.recipient_email
    end
    current_user.opens.each do |post|
      all_senders_and_receivers <<  User.find_by(id: post.sender_id).email
    end
    @uniq_senders_receivers = all_senders_and_receivers.uniq
  end

  def create
    if @recipient = User.find_by(email: params[:post][:recipient_email])
      params[:post][:recipient_id] = @recipient.id
    else
      @recipient = User.create(name: params[:post][:recipient_email], email: params[:post][:recipient_email], username: params[:post][:recipient_email], password: "OpenWhen")
      params[:post][:recipient_id] = @recipient.id
    end
    @post = Post.new(post_params)
    if @post.save
      UserMailer.new_openwhen(@recipient).deliver_now
      flash[:send_success] = "Success! Your OpenWhen has been sent! Rejoice!"
      redirect_to '/'
    else
      flash[:send_failure] = "Unfortunately, you need some critical fields. Please try again!"
      redirect_to '/posts/new'
    end
  end


  def index
    if params[:q]
      user_search = User.where("name LIKE ? OR username LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%")
      tag_search = Tag.where("name LIKE ?", "%#{params[:q]}%")
      search_items = !user_search.empty? || !tag_search.empty?
      if search_items && !user_search.empty?
        @posts =
        user_search.map do |search_result|
          Post.where(sender_id: search_result.id, recipient_id: current_user.id)
        end.flatten.uniq
      elsif search_items && !tag_search.empty?
        # first, find all the PostTag objects
        # then, find all the posts
        all_post_tags =
        tag_search.map do |search_result|
          PostTag.where(tag_id: search_result.id)
        end.flatten.uniq
        @posts =
        all_post_tags.map do |post_tag_object|
          Post.where(id: post_tag_object.post_id, recipient_id: current_user.id)
        end.flatten.uniq
      else
        flash[:search] = "Sorry! Your search did not turn up any results."
        @posts = Post.where(recipient_id: current_user.id)
        redirect_to posts_path
      end
    else
      if params[:category_id]
        @posts = Post.all.select {|post| post.recipient_id == current_user.id && post.category.id == params[:category_id].to_i}
      else
        @posts = Post.all.select{|post| post.recipient_id == current_user.id}
      end
    end
    # <%= form_tag(category_posts_path(params[:category_id]), method: "get") do %>
    # <%= label_tag(:q, "Search for") %>
    # <%= select_tag "search_by",options_for_select([ "tag", "sender" ], :search_input) %>
    # <%= text_field_tag(:q) %>
    # <%= submit_tag("Search") %>
    # <% end %>
    # <br>
    #
    #
    # ActionController::Parameters {"utf8"=>"✓", "search_by"=>"sender", "q"=>"dkjfsf", "commit"=>"Search", "controller"=>"posts", "action"=>"index", "category_id"=>"1"} permitted: false>
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      redirect_to edit_post_path(@post)
    end
  end

  def read
    @post = Post.find(params[:id])
    @post.read_status = true
     if @post.read_time.nil?
       @post.read_time = Time.now
     end
    @post.save
    redirect_to post_path(@post)
  end

  def unread
    @post = Post.find(params[:id])
    @post.read_status = false
    @post.read_time = nil
    @post.save
    redirect_to category_posts_path(@post.category)
  end

  def all_posts
    @posts = Post.where(recipient_id: current_user.id)
  end


  private
  def post_params
    params.require(:post).permit(:title, :content, :category_id, :sender_id, :recipient_id, :recipient_email, :read_status, :read_time, tags_attributes: [:name])
  end
end


# create_table "posts", force: :cascade do |t|
#   t.string "title"
#   t.string "content"
#   t.integer "category_id"
#   t.integer "sender_id"
#   t.integer "recipient_id"
#   t.string "recipient_email"
#   t.boolean "read_status", default: false
#   t.datetime "read_time"
#   t.datetime "created_at", null: false
#   t.datetime "updated_at", null: false
# end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/all_posts.html.erb
<%= flash[:search] %>
<h4> All your notes </h4>

<br>


<%= form_tag(keepsakes_path, method: "get") do %>
<%= label_tag(:q, "Search for") %>
<%= select_tag "search_by",options_for_select([ "tag", "sender" ], :search_input) %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search", class: 'btn btn-sm btn-primary') %>
<% end %>
<br>
<br>



<table>
  <tr>
    <th></th>
    <th></th>
  </tr>


<% @posts.each do |post| %>
  <tr>
  <td style="padding: 0 10px 0 0">
    <% if post.read_status == false%>
      <%= image_tag 'heart.png', height: 10, width: 10 %>
    <% end %>
  </td>
    <td style="padding: 0 10px 0 0">
      <% if post.read_status == false%>
        <strong><%= link_to post.title, post_read_path(post), method: :post %></strong>
      <% else %>
        <%= link_to post.title, post_read_path(post), method: :post %>
      <% end %></td>

    <td style="padding: 0 10px 0 0">
    </td>
    </tr>
<% end %>

</table>

<br>
<br>
<%= link_to "All Envelopes", home_path%>

app/views/posts/backup.html.erb
<!-- our former logic for posts table -->

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
  <td style="padding: 0 10px 0 0">
    <% if post.read_status == false%>
      <%= image_tag 'heart.png', height: 10, width: 10 %>
    <% end %>
  </td>
    <td style="padding: 0 10px 0 0">
      <% if post.read_status == false%>
        <strong><%= link_to post.title, post_read_path(post), method: :post %></strong>
      <% else %>
        <%= link_to post.title, post_read_path(post), method: :post %>
      <% end %></td>

    <td style="padding: 0 10px 0 0">
      <% if post.read_status == true %>
          <%= button_to "Mark as unread", post_unread_path(post), class: 'btn btn-xs btn-primary' %>
      <% end %>
    </td>
    </tr>
<% end %>

</table>

<br>
<br>
<%= link_to "All OpenWhens", home_path%>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <%=f.hidden_field :sender_id %><br>
  <%=f.hidden_field :recipient_id %><br>

  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :content %><br>
  <%= f.text_area :content %><br>
  <%= f.label :category %>
  <%= f.select :category_id, Category.all.map {|c| [c.name, c.id]} %><br>
  <%=f.fields_for :tags do |tag| %>
    <%= tag.label :tag %>
    <%= tag.text_field :name %><br>
  <% end %>
  <%= f.submit "Edit this OpenWhen", class: 'btn btn-large btn-primary' %>
<% end %>

app/views/posts/index.html.erb
<%= flash[:search] %>
<br>

<%= link_to "All envelopes", home_path%>
<% if params[:category_id] %>
<h4> Open when you're: <%= Category.find(params[:category_id]).name %> </h4>
<% end %>
<br>



<% @posts.each do |post|   %>
    <% if post.read_status == false%>
     <div class="col-sm-4">
       <div class="card">
         <div class="card-block">
           <h3 class="card-title"></h3>
           <p class="card-text"></p>
            <%= button_to "#{post.title}", post_read_path(post), method: :post, class: 'btn btn-postit-unread' %>
            <!-- <input type="checkbox" value=""> -->
        </div>
      </div>
     </div>
     <% else %>
     <div class="col-sm-4">
      <div class="card">
        <div class="card-block">
          <h3 class="card-title"></h3>
          <p class="card-text"></p>
             <%= button_to "#{post.title}", post_read_path(post), class: 'btn btn-postit-read' %>
        </div>
      </div>
     </div>
   <% end %>
<% end %>
<br>
<br>

app/views/posts/new.html.erb
<%= flash[:send_failure]  %>

<div class="col-sm-6">


<%= form_for @post do |f| %>
  <%=f.hidden_field :sender_id, value: current_user.id %>
<div class="form-group">
  <%= f.label :'You want your loved one to open when:' %>
  <%= f.select :category_id, Category.all.map {|c| [c.name, c.id]}, {} ,{class: 'form-control'} %>
</div>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control" %>
</div>
<div class="form-group">
  <%=f.fields_for :tags do |tag| %>
    <%= tag.label :tag %>
    <%= tag.text_field :name, class: "form-control" %>
  <% end %>
</div>
<div class="form-group">
  <%= f.label :recipient_email %>
  <%= f.text_field :recipient_email, list: "recipient_autocomplete", class: "form-control" %>
  <datalist id="recipient_autocomplete">
    <% @uniq_senders_receivers.each do |email| %>
    <option value="<%=email%>" >
      <% end %>
   </datalist>
</div>
  <%= f.submit "Send an OpenWhen", class: 'btn btn-large btn-primary' %><br></br>
<% end %>

</div>

app/views/posts/show.html.erb
<div class="col-sm-6">
<h1><%= @post.title %></h1><br>

<strong>From:</strong> <%= User.find_by(id: @post.sender_id).name.titleize %>

<br><br>
<p class="well"><%= @post.content %></p>
Read: <%= @post.read_time.strftime("%A, %B %d, %Y at %l:%M %P") %>
<br><br>
<div class="float-left"><strong>Tags: </strong>
</div><br>
  <% @post.tags.each do |tag| %>
  <div class="col-sm-2">
    <button type="button" class="btn btn-xs btn-primary"><%= tag.name %></button>
  </div>
  <% end %>
<br><br>
<%= link_to "Back", category_posts_path(@post.category)%>
</div>