config/routes.rb
Rails.application.routes.draw do
  resources :post_tags
  resources :categories
  resources :posts
  resources :users



  post '/posts/:id/read', to: 'posts#read',  as: 'post_read'
  post '/posts/:id/unread', to: 'posts#unread',  as: 'post_unread'
  get '/allthefeels', to: 'application#allthefeels', as: 'analytics'



  resources :categories do
    resources :posts
  end


  root 'application#home', as: 'home'
  get '/login', to: "sessions#new", as: 'login'
  post '/login', to: "sessions#create"
  delete '/sessions', to: "sessions#destroy", as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user




  def logged_in?
    !!session[:user_id]
  end

  def home
    if !logged_in?
      redirect_to login_path
    end
  end

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end

  def allthefeels
    all_durations = Visit.all[0...-1].map do |visit|
      if !visit.ended_at
        visit.ended_at = Time.now
      else
        (visit.ended_at - visit.started_at)/60
      end

    end

    @total_duration = all_durations.inject(:+)
    @longest_duration = all_durations.max

    top_senders = User.all.select{|user| user.posts.count > user.opens.count}
    @ratio = ((top_senders.count.to_f / User.all.count) * 100)

    @most_popular_category = Category.all.max_by {|category| category.posts.count}

    @top_three_tags = Tag.all.max_by(3) {|tag| tag.posts.count}.reverse
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/allthefeels.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>All the Feels...</title>
  </head>
  <body>
    <h1>All the Feels...</h1>

     <strong> Your longest visit: </strong> <%= current_user.max_duration.round(2) %> minutes <br>
     <strong> Average time you've spent on OpenWhen: </strong> <%= current_user.average_duration.round(2) %> minutes<br>


     <strong> Total users: </strong> <%= User.all.count %><br>
     <% if User.all.count > 2 %>
       <strong> Total minutes spent by all users on platform: </strong> <%= @total_duration.round(2) %><br>
       <strong> Longest visit to OpenWhen: </strong> <%= @longest_duration.round(2) %> minutes<br>
       <strong> Average minutes spent per visit to OpenWhen: </strong> <%= (@total_duration / Visit.all.count).round(2) %><br>
       <strong> Total notes exchanged: </strong> <%= Post.all.count %><br>
       <strong> Percentage who send more than they receive: </strong> <%= @ratio.round(0) %>%<br>
       <strong> Most popular category: </strong> <%= @most_popular_category.name %><br>
       <strong> Most popular tags:</strong>
          <ol>
            <% @top_three_tags.each do |tag| %>
            <li><%= tag.name %>: <%=Tag.where(name: tag.name).count%> notes</li>
            <%end%>
          </ol>
    <% end %>
  <br>


  </body>
</html>

app/views/application/home.html.erb
<div class="col-sm-6" >
<h1>Welcome, <%=current_user.name.titleize %>! </h1><br>
</div>
<div class="col-sm-6 new-post">
    <%= button_to "Write a new OpenWhen", new_post_path, method: :get, class: 'btn btn-large btn-primary' %><br>
</div>
<div class="col-sm-12">
<%= flash[:send_success]  %><br>
</div>
<div class="col-sm-12">
      <% if !current_user.opens.empty? %>
        <% current_user.categories.uniq.each do |category|   %>
         <% if category.posts.count > 1 %>
           <div class="col-sm-4">
             <div class="card">
               <div class="card-block">
                 <h3 class="card-title"></h3>
                 <p class="card-text"></p>
                   <%= button_to "Open When...You're #{category.name}", category_posts_path(category), method: :get, class: 'btn btn-custom' %>
               </div>
             </div>
           </div>
        <% else %>
          <div class="col-sm-4">
            <div class="card">
              <div class="card-block">
                <h3 class="card-title"></h3>
                <p class="card-text"></p>
                  <%= button_to "Open When... You're #{category.name}", post_read_path(category.posts.first), method: :post, class: 'btn btn-custom' %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
</div>