config/routes.rb
Rails.application.routes.draw do
  resources :post_tags
  resources :categories
  resources :posts
  resources :users



  post '/posts/:id/read', to: 'posts#read',  as: 'post_read'
  post '/posts/:id/unread', to: 'posts#unread',  as: 'post_unread'
  get '/allthefeels', to: 'application#allthefeels', as: 'analytics'



  resources :categories do
    resources :posts
  end


  root 'application#home', as: 'home'
  get '/login', to: "sessions#new", as: 'login'
  post '/login', to: "sessions#create"
  delete '/sessions', to: "sessions#destroy", as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Open When...</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"></link>
  </head>
  <body>
    <div class="row">

    <!--  navbar -->
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="active" id="logo"><a href="<%= home_path %>">OpenWhen</a></li>
                  <% if logged_in? %>

                  <!-- our search -->

                    <li>
                  <%= form_tag(posts_path, method: "get", class: 'navbar-form navbar-left', role: 'search') do %>
                    <div class="form-group">
                    <%= text_field_tag(:q, "", class: 'form-control', placeholder: 'Search by tag/sender') %>
                    </div>
                    <%= submit_tag("Search", class: 'btn btn-default') %>
                  <% end %>
                </li>

                  <!-- end search  -->


                  <ul class="nav navbar-nav navbar-right">
                    <li ><a href="<%=new_post_path%>"><span class="glyphicon glyphicon-pencil"></span> Compose</a></li>
                    <li ><a href="<%=analytics_path%>"><span class="glyphicon glyphicon-tasks"></span> All the Feels</a></li>
                    <li ><a href="<%=user_path(current_user)%>"><span class="glyphicon glyphicon-user"></span> Account</a></li>
                     <li><a href="<%=logout_path%>" data-method="delete"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
                  </ul>
                 <% else %>
                 <ul class="nav navbar-nav navbar-right pull-right">
                    <li ><a href="<%=new_user_path%>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href="<%=login_path%>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
                <% end %>
              </li>




<!-- end               -->
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
    </div>
    <!-- content -->
    <div class="row">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>